name: Go Httpbin
run-name: ${{ github.actor }} is running a job
on:
  push:
    tags:
      - v**
jobs:
  Build-image-httpbin:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Etract Release Version
        run: |
          echo "GITHUB_REF = ${GITHUB_REF}"
          echo "GITHUB_REF#refs = ${GITHUB_REF#refs}"
          echo "GITHUB_REF#refs/*/ = ${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION = ${{ env.RELEASE_VERSION }}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  