name: Go Httpbin
run-name: ${{ github.actor }} is Building the Httpbin image
on:
  push:
    tags:
      - v**
jobs:
  Build-image-httpbin:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Etract Release Version
        run: |
          echo "GITHUB_REF = ${GITHUB_REF}"
          echo "GITHUB_REF#refs = ${GITHUB_REF#refs}"
          echo "GITHUB_REF#refs/*/ = ${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sjulian/go-httpbin:${{ env.RELEASE_VERSION  }}
  